spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true

logging:
  level:
    #    org.springframework: debug
    sql: trace

tests:
  name: fischer

